language: node_js
node_js:
- '12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=orange)
  - secure: Qe1ZWrDJoemkoqQS5JeJYpSRUeVWOFHgaz9RjdgI18mHD70JoWHdCWIhsY1yf9uG9pnWN/gb6G/ANNxDK83tEj/zvVam+KH56QUI1yHeWxrngax9ggyx5S6my1ozYPV5UylhpvYYNzg6lhCVe0aAMTayRzYw8ocRN72gdoFzWOjE/5XYD6lnMOY+XzKv7ag5Ui43kD3Q5AYv5jwEmzSOC/yREmjtT5ssFev3tghgZBYRstUnw9gknj6eAZX8Xmyc8xvn9dVIJfWY7QsE59FKu0Y7vuqlPXq3Pkcy5XesxPJTkhJ2jqfBu2pNk+vRgbd5wqpPx9EwwAORNOSBY92Fq6QmntDxLfSs237IX5JhZMN3zpCCR44BNWF/W1nGt0bIZbbW9ttvL5UzgI6Av/u4F6KM86OayF1JyHPWm82XLlbnnzwyrwUJhCvR2WNhznIFoKIj4yQ8dxQmWNu4xMh0a0yerFBfHteVJx8/dVJFOlXwJ12tB9F5R3xSIR6kEUGYXbL1PSlUvRWEZtxTbuGJySTdaS2X6niZb2OngKgDwi5QwYFIVEB4QTRrXhxjqyqqlL+5P6OWHZ84GRIGHrrUJy0ukd+x8hGjmXSFW609oiWBuB9V0iwfVPPvmbnAClG4RIzRcQXfIHAqGEZyfbX2PIWbymBiUsReY2SyPjxfOgM=
  # MATTERMOST_HOOK_URL
  - secure: jP0IEozN/t8NQYoq5oIHisG2T6ejaDKbgyTQ09lPhAiRasldyQtCFudglyubKVcVqZFrSvCxR0EmXQ9pkvo0Ye6qpMJnJngxtrWRlReKCGqjU4U60dIOJiT7nMrAG2n7FF6M1/Yr6ChiGHk9CrehQPGftVWSoaAM90CShxnobsfdzbanHS1R9kkk8MZ8DBqkZHyqlAkA+b6xQrq4s/FFRgH4AmMYCaxWW7cYesPoSQyaq2ifIO0MtqrlPIo598NLgI7x7YZpXabFP04KKzFox6z4SqVJjW9sPrYsjK4DckO6Rdp1+MK/tlreuu5kcR+Gg04pmtL6KR7N3UloCoG2OebLAiFJYBW0WNayb7GmTNJxMqi54PG4TMnMH5r2g2d7TnP9cNK1KDqfY4m8JmFOAsxy2BUhYHgv8sw//2uPQfT04MWKQnOw92GAjANQVb7JXnPZiHKEstfOqGGaaJNBfRx90oikMAuVzjDkDIrTORgZEjm24PSonN5B8c8Xc09UxVtYdDq4c9HmuMke9we5GZ/I2F5ZoPnFzf+craHFDE2mXNUcbXjPwx5d7RnFqvm5ICp2kAriN5rwAFPozkdc68ShzzdpnRihHdV/R5UpCM+gH7QWdSI7Q3EIW68VaP7793SDObqJqaeVc3H4Bt2K7pJbT8SVO3EuiA2sgNfUE5Y=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_1a2d187681d9_key -iv $encrypted_1a2d187681d9_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
